#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Job System production setup"

stage "OpenAI API"
say "Create a project API key. It is stored only in the local env file."
open_url "https://platform.openai.com/api-keys"
step "Create or select a project, create a secret key, and copy it once."
ask_secret OPENAI_API_KEY "Paste OPENAI_API_KEY:"
ask OPENAI_MODEL "Model name (recommended: gpt-5.6-luna):"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"
write_env OPENAI_MODEL "${OPENAI_MODEL:-gpt-5.6-luna}"

stage "Tavily search"
say "Create a Tavily API key for the primary web-search provider."
open_url "https://app.tavily.com/home"
step "Open API Keys and copy the active key."
ask_secret TAVILY_API_KEY "Paste TAVILY_API_KEY:"
write_env TAVILY_API_KEY "$TAVILY_API_KEY"

stage "Brave Search fallback"
say "Create a Brave Search API key for provider fallback."
open_url "https://api.search.brave.com/app/keys"
step "Select the Search API subscription and copy an API key."
ask_secret BRAVE_SEARCH_API_KEY "Paste BRAVE_SEARCH_API_KEY:"
write_env BRAVE_SEARCH_API_KEY "$BRAVE_SEARCH_API_KEY"

stage "Telegram MTProto reader (optional)"
say "The reader account is independent from the notification bot. You may skip it and re-run later."
if confirm "Configure MTProto reader now?"; then
  open_url "https://my.telegram.org/apps"
  step "Sign in, open API development tools, create an app, then copy api_id and api_hash."
  ask TELEGRAM_API_ID "Paste TELEGRAM_API_ID:"
  ask_secret TELEGRAM_API_HASH "Paste TELEGRAM_API_HASH:"
  ask TELEGRAM_SESSION_PATH "Session path (recommended: /app/private/telegram-reader.session):"
  write_env TELEGRAM_API_ID "$TELEGRAM_API_ID"
  write_env TELEGRAM_API_HASH "$TELEGRAM_API_HASH"
  write_env TELEGRAM_SESSION_PATH "${TELEGRAM_SESSION_PATH:-/app/private/telegram-reader.session}"
else
  SKIPPED+=("Telegram MTProto reader (re-run this wizard later)")
fi

stage "Telegram notification bot"
say "Use the dedicated @job_search_881_bot token and your numeric owner chat id."
open_url "https://t.me/BotFather"
step "Open the bot, use /token if necessary, and copy its token."
ask_secret TELEGRAM_BOT_TOKEN "Paste TELEGRAM_BOT_TOKEN:"
step "Send the bot a message, then obtain the numeric chat id from a trusted Bot API getUpdates call."
ask TELEGRAM_OWNER_CHAT_ID "Paste TELEGRAM_OWNER_CHAT_ID:"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_OWNER_CHAT_ID "$TELEGRAM_OWNER_CHAT_ID"

stage "Domain and VPS"
say "Confirmed target: job.web3babka.su on 169.58.93.185. These values are public."
ask JOB_DOMAIN "Domain (recommended: job.web3babka.su):"
ask JOB_VPS_IP "VPS IPv4 (recommended: 169.58.93.185):"
JOB_DOMAIN="${JOB_DOMAIN:-job.web3babka.su}"
JOB_VPS_IP="${JOB_VPS_IP:-169.58.93.185}"
write_env JOB_DOMAIN "$JOB_DOMAIN"
write_env JOB_VPS_IP "$JOB_VPS_IP"
write_env JOB_SITE_URL "https://$JOB_DOMAIN"
write_env DJANGO_ALLOWED_HOSTS "$JOB_DOMAIN,localhost,127.0.0.1"
write_env DJANGO_CSRF_TRUSTED_ORIGINS "https://$JOB_DOMAIN"
ask_secret DJANGO_SECRET_KEY "Paste a new high-entropy DJANGO_SECRET_KEY:"
write_env DJANGO_SECRET_KEY "$DJANGO_SECRET_KEY"
write_env DJANGO_DEBUG "false"
write_env DJANGO_SECURE_SSL_REDIRECT "true"
write_env DJANGO_SECURE_HSTS_SECONDS "31536000"

stage "Encrypted backups"
say "Generate the age identity on a trusted workstation. Never copy the private identity to the VPS."
open_url "https://github.com/FiloSottile/age#usage"
step "Off-server, run: age-keygen -o job-system-backup-key.txt"
step "Store that private file in a password manager/offline vault; copy only its public age1... recipient."
ask BACKUP_AGE_RECIPIENT "Paste the public age1... recipient:"
write_env BACKUP_AGE_RECIPIENT "$BACKUP_AGE_RECIPIENT"

finish
