# Generated by Django 5.2.17 on 2026-09-20 13:10

import django.db.models.deletion
import jobs.models.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('holder', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirmed_version', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('kind', models.CharField(max_length=64)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_version', models.PositiveIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='models.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private_path', models.CharField(max_length=500)),
                ('text', models.TextField(blank=True)),
                ('extraction_state', models.CharField(choices=[('pending', 'Ожидает'), ('complete', 'Извлечено'), ('error', 'Ошибка')], default='pending', max_length=16)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='models.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('uncertain', 'Неизвестно')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('last_error_message', models.CharField(blank=True, max_length=500)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='models.run')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=32)),
                ('adapter', models.CharField(max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Без секретов')),
                ('status', models.CharField(choices=[('ready', 'Работает'), ('limited', 'Ограниченная выдача'), ('needs_access', 'Нужны данные доступа'), ('not_configured', 'Не настроено'), ('error', 'Ошибка')], default='not_configured', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('cursor', models.TextField(blank=True)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('llm_permission', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('canonical_url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('raw_hash', models.CharField(max_length=128)),
                ('description_permission', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='models.source')),
            ],
        ),
        migrations.CreateModel(
            name='TemporarySourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.FileField(storage=jobs.models.storage.TemporaryContentStorage(), upload_to='source-content/%Y/%m/%d')),
                ('expires_at', models.DateTimeField()),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_content', to='models.sourcerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=50)),
                ('units', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=50)),
                ('units', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('company_domain', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('work_arrangement', models.CharField(blank=True, max_length=50)),
                ('country_restrictions', models.JSONField(blank=True, default=list)),
                ('timezone_restrictions', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=3)),
                ('salary_period', models.CharField(blank=True, max_length=20)),
                ('salary_basis', models.CharField(blank=True, max_length=50)),
                ('salary_component', models.CharField(blank=True, max_length=100)),
                ('salary_fixed', models.JSONField(blank=True, default=dict)),
                ('salary_bonus', models.JSONField(blank=True, default=dict)),
                ('salary_equity_tokens', models.JSONField(blank=True, default=dict)),
                ('salary_original', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.CharField(choices=[('new', 'Новая'), ('saved', 'Сохранена'), ('applied', 'Откликнулся'), ('interview', 'Интервью'), ('closed', 'Закрыта')], default='new', max_length=16)),
                ('availability', models.CharField(choices=[('unknown', 'Неизвестна'), ('active', 'Активна'), ('removed', 'Снята')], default='unknown', max_length=16)),
                ('hidden', models.BooleanField(default=False)),
                ('user_note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='models.vacancy'),
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=300)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('complete', 'Готово'), ('partial', 'Частично'), ('unavailable', 'Недоступно'), ('needs-domain', 'Нужен домен')], default='pending', max_length=20)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='models.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=32)),
                ('text', models.TextField(blank=True)),
                ('profile_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('editing', 'Редактируется'), ('generated', 'Сгенерирован'), ('limited', 'Ограничен'), ('error', 'Ошибка')], default='editing', max_length=16)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='models.profile')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='models.research')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='models.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_source_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_id_per_source'),
        ),
    ]
