# Generated by Django 5.2.17 on 2026-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sourcerecord',
            name='unique_external_id_per_source',
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='adapter_confirmed_permalink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='closing_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='priority',
            field=models.CharField(choices=[('remote', 'Удалённая'), ('relocation', 'Релокация'), ('other', 'Остальное')], default='other', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uniq_source_extid_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', '')), fields=('source', 'canonical_url'), name='uniq_source_url_no_extid'),
        ),
    ]
